hosts:
 - name: 192.168.1.105
   username: student
   password: Meilab123
   port: 22
   cmd: "show running-config"
   type: cisco_ios
 - name: 192.168.1.106
   username: student
   password: Meilab123
   port: 22
   cmd: "show running-config"
   type: cisco_ios